[package]
name = "essential-rest-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
clap = { workspace = true }
essential-server-types = { workspace = true }
essential-types = { workspace = true }
serde = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
tokio = { workspace = true }
